pub mod dedup_service;
pub mod history_service;
pub mod normalize_service;
pub mod paste_executor;
pub mod privacy_service;
pub mod search_service;
pub mod shortcut_manager;
pub mod tray_service;
pub mod window_coordinator;
